base {
    log_debug = off;
    log_info = on;
    log = stderr;
    daemon = on;
    redirector = iptables;
}

redsocks {
    local_ip = 127.0.0.1;
    local_port = 12345;

    /* Эти три поля перезаписываются сервером при каждом /set_proxy */
    ip = 0.0.0.0;
    port = 1080;
    type = socks5;
    login = "";
    password = "";
}
